apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rest-service-chart.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "rest-service-chart.name" . }}
    helm.sh/chart: {{ include "rest-service-chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "rest-service-chart.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "rest-service-chart.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: test-config-volume
              mountPath: "/spring-boot-service/config"
      volumes:
        - name: test-config-volume
          configMap:
            name: test-config
            items:
            - key: application.properties
              path: application.properties

