apiVersion: v1
kind: Service
metadata:
  name: test-service
  labels:
    app.kubernetes.io/name: {{ include "rest-service-chart.name" . }}
    helm.sh/chart: {{ include "rest-service-chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "rest-service-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
